"""WEB 계층 공부 2~10단계 Notion 원고 생성. 값은 2026-09-17 mc-deploy 실측."""
import os, re
OUT = os.path.dirname(os.path.abspath(__file__))
def T(rows):
    o = ['<table header-row="true" fit-page-width="true">']
    for r in rows:
        o.append("\t<tr>"); o += [f"\t\t<td>{c}</td>" for c in r]; o.append("\t</tr>")
    o.append("</table>"); return "\n".join(o)
def code(lang, body): return f"\n```{lang}\n{body}\n```\n"
def Q(q, a): return f"<details>\n<summary>{q}</summary>\n\t{a}\n</details>"
def goal(icon, text): return f'<callout icon="{icon}" color="blue_bg">\n\t{text}\n</callout>'
def road(n, name):
    steps = ["0 VPC 입구", "1 HTTP 기초", "2 TLS 종료 지점", "3 ALB 해부", "4 오리진 보호(헤더)", "5 헬스체크", "6 Apache 프록시", "7 분산·타임아웃", "8 WEB 관측", "9 장애 모드", "10 ASG·AMI"]
    steps[n] = f"**{steps[n]}(이 페이지)**"
    return f'<callout icon="🗺️" color="gray_bg">\n\t**로드맵 위치**: {" → ".join(steps)}.\n</callout>'
CF_ALB = "mc-alb-public-485062926.ap-northeast-2.elb.amazonaws.com"
pages = {}

# ---------------- 2 TLS ----------------
pages[2] = ("2단계 — TLS 종료 지점: 자물쇠는 두 번 풀리고, 마지막 구간은 평문이다", "2️⃣", "\n".join([
goal("🔐", "**이 단계의 목표**: HTTPS(자물쇠)가 어디서 잠기고 어디서 풀리는지, 인증서가 왜 2장인지, 보안 정책 이름이 무슨 뜻인지. 그리고 그 결과로 Apache 가 \"나는 http\" 라고 믿게 되는 이유. 하루 분량."),
"# 0. 그림 한 장",
code("text", "브라우저 ══HTTPS(인증서 A: us-east-1)══▶ CloudFront ══HTTPS(인증서 B: 서울)══▶ ALB ──평문 HTTP 80──▶ Apache ──평문 HTTP 8080──▶ Internal ALB ──▶ Tomcat\n            ▲ 1차 종료(TLS 풀림)                          ▲ 2차 종료(TLS 풀림)        X-Forwarded-Proto: https 로 \"원래 https 였음\" 만 전달"),
"\"TLS 종료(termination)\" = 암호를 풀고 평문을 보는 지점. 우리는 **두 곳**(CloudFront · ALB)에서 풀고, VPC 안(ALB → Apache → Internal ALB → Tomcat)은 **평문**으로 간다.",
"# 1. 왜 두 번 풀고, 왜 안은 평문인가",
T([("구간", "암호화", "왜"),
   ("브라우저 → CloudFront", "HTTPS · 인증서 A(us-east-1)", "공용 인터넷. CloudFront 가 캐시·WAF 판단을 하려면 내용을 봐야 하므로 여기서 한 번 푼다"),
   ("CloudFront → ALB", "HTTPS · 인증서 B(서울) · 오리진 프로토콜 **https-only** · TLSv1.2", "역시 공용 인터넷(0단계). CloudFront 가 ALB 의 인증서 이름(`petclinic.mission-critical.site`)을 검증한다 — 그래서 Host 를 AllViewer 로 넘겨야 이름이 맞는다"),
   ("ALB → Apache", "**평문 80**", "VPC 안, SG 로 격리된 사설망. 여기까지 암호화하면 인증서를 서버마다 두고 갱신해야 해서 운영 부담만 늘어남(요구되면 대상 그룹 HTTPS 로 가능)"),
   ("Apache → Internal ALB → Tomcat", "평문 8080", "동일"),
   ("Tomcat → RDS Proxy", "**TLS 필수**(sslMode=REQUIRED)", "DB 는 개인정보라 사설망 안이라도 암호화 — WAS 단계에서")]),
"# 2. 인증서가 2장인 이유",
T([("인증서", "리전", "붙는 곳", "실측"),
   ("A", "**us-east-1(버지니아)**", "CloudFront 뷰어 인증서 — CloudFront 는 글로벌 서비스라 **us-east-1 의 ACM 만** 받는다", "`petclinic.mission-critical.site` · ISSUED · 만료 2027-04-01 · 자동 갱신"),
   ("B", "**ap-northeast-2(서울)**", "ALB 443 리스너 — ALB 는 리전 리소스라 **같은 리전의 ACM 만** 받는다", "`petclinic.mission-critical.site` · ISSUED · RSA-2048 · 만료 2027-04-01")]),
"둘 다 **같은 도메인 · 같은 DNS 검증 CNAME** 이라 Route 53 레코드는 하나. ACM 이 60일 전부터 자동 갱신하니 그 CNAME 을 지우면 안 된다(콘솔 가이드 ①-4).",
"# 3. 보안 정책 이름 읽기",
T([("이름", "뜻"),
   ("ALB `ELBSecurityPolicy-TLS13-1-2-2021-06`", "**TLS 1.3 과 1.2** 만 허용(1.0·1.1 거부) · 2021-06 판 암호 스위트 묶음. 실측 로그: `TLSv1.3 TLS_AES_128_GCM_SHA256`"),
   ("CloudFront `TLSv1.2_2021`", "뷰어와 협상할 최소 버전 TLS 1.2 · 2021 스위트. 오래된 브라우저(TLS 1.0)는 접속 불가 — 의도된 것"),
   ("SNI", "한 IP 로 여러 도메인의 인증서를 고르는 방식. CloudFront `sni-only` = 전용 IP 비용 없이"),
   ("HTTP/2 · HTTP/3", "브라우저 ↔ CloudFront 는 `http2and3`. CloudFront → ALB 는 HTTP/1.1(오리진은 항상 1.1). ALB `routing.http2.enabled=true` 는 뷰어용이지만 우리 뷰어는 CloudFront 뿐")]),
"# 4. 그래서 생기는 일 — Apache 는 https 를 모른다",
"ALB 가 자물쇠를 풀고 평문 80 으로 넘기므로 Apache 입장에선 **모든 요청이 http**. 원래 https 였다는 사실은 ALB 가 붙이는 `X-Forwarded-Proto: https` 헤더로만 안다. 그래서 Apache 가 리다이렉트를 만들 때 이 헤더를 먼저 본다(6단계). 안 보면 `Location: http://…` 를 돌려주고, CloudFront 가 http→https 로 다시 보내서 **루프**.",
"# 5. 눈으로 확인",
code("bash", f"# 1) 뷰어 쪽 TLS — 어떤 버전·스위트·인증서로 붙었나 (CloudFront 인증서 A)\ncurl -svo /dev/null https://petclinic.mission-critical.site/ 2>&1 | grep -E \"SSL connection|subject:|issuer:|expire\"\n\n# 2) ALB 쪽 인증서 B — SNI 로 이름을 주고 직접 (403 이 정상 · 인증서만 확인)\ncurl -svo /dev/null --resolve petclinic.mission-critical.site:443:$(dig +short {CF_ALB} | head -1) https://petclinic.mission-critical.site/ 2>&1 | grep -E \"SSL connection|subject:|HTTP/\"\n\n# 3) 리스너 보안 정책 · 인증서 ARN\naws elbv2 describe-listeners --load-balancer-arn $(aws elbv2 describe-load-balancers --names mc-alb-public --query 'LoadBalancers[0].LoadBalancerArn' --output text --profile mc-deploy) --profile mc-deploy --query 'Listeners[].[Port,SslPolicy,Certificates[0].CertificateArn]' --output table\n\n# 4) ACM 두 장 (서울 · us-east-1)\naws acm list-certificates --profile mc-deploy --region ap-northeast-2 --query 'CertificateSummaryList[].[DomainName,Status,NotAfter]' --output table\naws acm list-certificates --profile mc-deploy --region us-east-1      --query 'CertificateSummaryList[].[DomainName,Status,NotAfter]' --output table"),
T([("확인", "기대 결과", "배우는 것"),
   ("1", "`TLSv1.3` · `subject: CN=petclinic.mission-critical.site` · issuer Amazon", "브라우저가 만나는 자물쇠는 CloudFront 것"),
   ("2", "같은 CN 의 인증서 + `HTTP/1.1 403`", "ALB 도 같은 이름의 인증서(B) — 다만 도장 없이는 403"),
   ("3", "`443 ELBSecurityPolicy-TLS13-1-2-2021-06 arn:aws:acm:ap-northeast-2:…`", "리스너에 서울 인증서"),
   ("4", "서울 1장 · us-east-1 1장, 둘 다 ISSUED", "인증서 2장의 이유")]),
"# 6. 다음 단계 진입 기준",
Q("Q1. ALB 에 us-east-1 인증서를 붙일 수 있나? CloudFront 에 서울 인증서는?", "둘 다 불가. ALB 는 자기 리전(서울) ACM 만, CloudFront 는 us-east-1 ACM 만. 그래서 같은 도메인으로 2장."),
Q("Q2. ALB → Apache 를 평문으로 두는 게 왜 허용되나?", "VPC 사설망 + SG 로 격리돼 외부가 볼 수 없는 구간이라 위험 대비 운영 비용이 크다. 규제로 요구되면 대상 그룹을 HTTPS 로 바꾸고 Apache 에 인증서를 두면 된다. DB 구간은 개인정보라 사설망이어도 TLS."),
Q("Q3. TLS 1.0 브라우저가 우리 사이트에 접속하면?", "CloudFront 가 `TLSv1.2_2021` 정책으로 거부(핸드셰이크 실패). 의도된 동작."),
"# 7. 읽을 자료", "- AWS 문서 — *Security policies for your Application Load Balancer* (정책 이름표)", "- AWS 문서 — *Requirements for using SSL/TLS certificates with CloudFront* (us-east-1 이유)", "- 콘솔 구축 가이드 **2-1 · 4-1 · 4-3** 절",
road(2, "")]))

# ---------------- 3 ALB ----------------
pages[3] = ("3단계 — ALB 해부: 리스너 → 규칙 → 대상 그룹 → 대상", "3️⃣", "\n".join([
goal("🧩", "**이 단계의 목표**: ALB 를 부품 4개(리스너 · 규칙 · 대상 그룹 · 대상)로 분해해서, 요청 하나가 어느 부품을 어떤 순서로 지나는지 콘솔 화면과 1:1 로 맞춘다. 하루 분량."),
"# 0. 그림 한 장",
code("text", "                 ┌─ 리스너 443 (TLS 풀기 · 보안 정책) ─────────────────────────────┐\n요청 ──▶ [SG] ──▶ │  규칙 10: 헤더 X-Origin-Verify == 비밀값 ?  → forward mc-tg-web │ ──▶ 대상 그룹 mc-tg-web ──▶ 대상 i-01a1…(web-a) :80\n                 │  기본 작업: fixed-response 403                                  │        (헬스체크 · 알고리즘)   대상 i-01d1…(web-c) :80\n                 └───────────────────────────────────────────────────────────────┘"),
"# 1. 부품 4개",
T([("부품", "하는 일", "우리 값 (실측)", "콘솔 위치"),
   ("**로드 밸런서**", "노드가 있는 서브넷·SG·속성(유휴 시간 등)을 가진 껍데기", "`mc-alb-public` · internet-facing · 서브넷 mc-public-a/c · SG mc-sg-alb-public · 유휴 60s · 교차 영역 on", "EC2 → 로드 밸런서"),
   ("**리스너**", "\"이 포트·프로토콜로 오는 연결을 받는다\" + TLS 종료 + 규칙 목록", "**443 HTTPS 하나뿐**(80 없음) · 정책 TLS13-1-2-2021-06 · 인증서 B", "로드 밸런서 → 리스너 및 규칙 탭"),
   ("**규칙**", "조건(경로·헤더·호스트·쿼리·IP…)이 맞으면 작업(forward · redirect · fixed-response · authenticate). **우선순위 숫자가 작은 것부터**, 맨 마지막이 **기본 작업**", "우선순위 **10**: `http-header X-Origin-Verify` 일치 → **forward mc-tg-web** · **기본**: fixed-response **403** `Forbidden`", "리스너 → 규칙 보기/편집"),
   ("**대상 그룹**", "보낼 서버들의 명단 + 포트 + 헬스체크 + 분산 알고리즘", "`mc-tg-web` · 인스턴스 · HTTP **80** · HTTP/1.1 · 헬스체크 `/health.html` 10s/5s/2/3 · 등록 취소 30s · **round_robin** · 스티키 off · slow start 0", "EC2 → 대상 그룹"),
   ("**대상**", "명단에 등록된 실제 서버 + 상태", "`i-01a195cff8acb28d8`(web-a) · `i-01d1734d081d8bc57`(web-c) 둘 다 **healthy**", "대상 그룹 → 대상 탭")]),
"# 2. 규칙 평가 — 위에서 아래로, 첫 매치에서 끝",
T([("순서", "규칙", "조건", "결과"),
   ("1", "우선순위 10", "요청 헤더 `X-Origin-Verify` 값이 우리 비밀값과 같다", "`mc-tg-web` 로 전달(forward). 여기서 끝 — 아래는 안 봄"),
   ("2", "기본(default)", "위에서 아무것도 안 맞음", "**403** 고정 응답. 대상에 닿지 않음")]),
"조건 유형 중 우리가 쓰는 건 `http-header` 하나. 경로 기반(`/api/*` → 다른 대상 그룹)이나 호스트 기반(도메인별) 분기도 같은 자리에서 한다 — WAS 를 API 서버와 나누게 되면 여기에 규칙이 늘어난다.",
"# 3. 대상 그룹이 하는 두 가지 일",
"- **누구에게 보낼지**: `round_robin` — 정상 대상에 번갈아. `교차 영역 on` 이라 2a 노드가 2c 서버로도 보낸다(AZ 균등).",
"- **누가 정상인지**: 10초마다 `/health.html` 을 GET, 5초 안에 200 이면 성공. 2번 연속 성공 → healthy, 3번 연속 실패 → unhealthy(5단계).",
"# 4. 요청 하나 따라가기 — `GET /petclinic/vets`",
"1. CloudFront 가 ALB 노드(0단계)로 HTTPS 연결 · 헤더에 `X-Origin-Verify` 를 붙여 보냄\n2. 리스너 443 이 TLS 를 풀고(2단계) 규칙 평가 시작\n3. 규칙 10 매치 → 대상 그룹 `mc-tg-web`\n4. 대상 그룹이 healthy 인 web-a/web-c 중 하나를 라운드로빈으로 선택, `10.0.10.189:80` 으로 평문 전달 · `X-Forwarded-For/Proto/Port` 헤더 추가\n5. Apache 응답 → ALB → CloudFront → 브라우저",
"# 5. 눈으로 확인",
code("bash", "ALB=$(aws elbv2 describe-load-balancers --names mc-alb-public --profile mc-deploy --query 'LoadBalancers[0].LoadBalancerArn' --output text)\n# 1) 리스너 — 443 하나, 기본 작업 403\naws elbv2 describe-listeners --load-balancer-arn $ALB --profile mc-deploy --query 'Listeners[].[Port,Protocol,DefaultActions[0].Type,DefaultActions[0].FixedResponseConfig.StatusCode]' --output table\n# 2) 규칙 — 우선순위 10 헤더 조건 → forward, default → fixed-response\nL=$(aws elbv2 describe-listeners --load-balancer-arn $ALB --profile mc-deploy --query 'Listeners[0].ListenerArn' --output text)\naws elbv2 describe-rules --listener-arn $L --profile mc-deploy --query 'Rules[].[Priority,Conditions[0].Field,Conditions[0].HttpHeaderConfig.HttpHeaderName,Actions[0].Type]' --output table\n# 3) 대상 그룹 속성 — 알고리즘 · 등록 취소 · 스티키\nTG=$(aws elbv2 describe-target-groups --names mc-tg-web --profile mc-deploy --query 'TargetGroups[0].TargetGroupArn' --output text)\naws elbv2 describe-target-group-attributes --target-group-arn $TG --profile mc-deploy --query 'Attributes[].[Key,Value]' --output table\n# 4) 대상과 상태\naws elbv2 describe-target-health --target-group-arn $TG --profile mc-deploy --query 'TargetHealthDescriptions[].[Target.Id,Target.Port,TargetHealth.State]' --output table"),
T([("확인", "기대 결과", "배우는 것"),
   ("1", "`443 HTTPS fixed-response 403`", "80 리스너가 없다 · 기본은 거부"),
   ("2", "`10 http-header X-Origin-Verify forward` · `default … fixed-response`", "규칙은 딱 하나, 나머지는 403"),
   ("3", "`load_balancing.algorithm.type round_robin` · `deregistration_delay 30` · `stickiness.enabled false`", "무상태 앱이라 스티키 불필요"),
   ("4", "두 인스턴스 `healthy`", "대상 = 실제 EC2, 상태는 헬스체크 결과")]),
"# 6. 다음 단계 진입 기준",
Q("Q1. 규칙 10 을 지우면 무슨 일이 생기나?", "모든 요청이 기본 작업 403 으로 떨어진다 — CloudFront 를 거친 정상 요청도. 사이트 전체가 403."),
Q("Q2. 80 리스너를 추가하고 tg-web 으로 forward 하면?", "ALB DNS 로 http 직접 접근이 열려 CloudFront·WAF 를 우회하는 길이 생긴다(4단계). 그래서 없앴다(`public_http_listener=false`)."),
Q("Q3. 대상 그룹의 포트 80 과 리스너 443 이 다른데 어떻게 되나?", "리스너는 뷰어(CloudFront) 쪽 포트, 대상 그룹 포트는 서버 쪽 포트. ALB 가 중간에서 443 → 80 으로 바꿔 보낸다(TLS 종료 = 2단계)."),
"# 7. 읽을 자료", "- AWS 문서 — *Listener rules for your Application Load Balancer* (조건·작업 유형 표)", "- AWS 문서 — *Target groups for your Application Load Balancers* (알고리즘 · 속성)", "- 콘솔 구축 가이드 **4-2 · 4-3** 절",
road(3, "")]))

# ---------------- 4 origin protection ----------------
pages[4] = ("4단계 — 오리진 보호: 출입문(SG)과 도장(X-Origin-Verify)을 둘 다 두는 이유", "4️⃣", "\n".join([
goal("🛡️", "**이 단계의 목표**: \"헤더를 왜 붙이나\" 를 위협 모델부터 이해한다. 누가 무엇을 우회하려 하고, SG 가 어디까지 막고, 헤더가 나머지를 어떻게 막는지. 반나절 분량."),
"# 0. 위협: CloudFront 를 건너뛰는 길",
code("text", "정상:   브라우저 ─▶ CloudFront(WAF · 캐시 · 로그) ─▶ ALB ─▶ WEB\n우회 ①: 공격자 ─────────────────────────────▶ ALB ─▶ WEB      ← ALB DNS/IP 를 알아내 직접 (WAF·rate limit·로그 전부 건너뜀)\n우회 ②: 공격자 ─▶ 자기 CloudFront 배포(오리진 = 우리 ALB) ─▶ ALB ─▶ WEB   ← CloudFront IP 대역은 통과하지만 우리 WAF 는 없음"),
"ALB DNS 이름은 비밀이 아니다(인증서 투명성 로그 · DNS 스캔으로 찾힘). 그러니 \"모르겠지\" 가 아니라 **막아야** 한다.",
"# 1. 두 겹 방어",
T([("겹", "무엇", "막는 것", "못 막는 것", "우리 값"),
   ("1차 **SG**", "ALB SG 인바운드 = CloudFront origin-facing 접두사 목록의 443 만", "우회 ① — 인터넷 어디서든 직접 오는 연결은 SG 에서 **타임아웃**(SYN 이 버려짐)", "우회 ② — 접두사 목록은 **전 세계 모든 CloudFront 배포가 공유**하는 IP", "`mc-sg-alb-public`: `443 ← pl-22a6434b` 한 줄"),
   ("2차 **비밀 헤더**", "우리 CloudFront 가 오리진 요청마다 `X-Origin-Verify: ‹비밀값›` 을 붙이고, ALB 규칙 10 이 그 값을 검사", "우회 ② — 남의 배포는 우리 비밀값을 모르니 **403**", "비밀값이 유출되면 무력 → 교체 절차 필요", "CloudFront 오리진 커스텀 헤더 = ALB 규칙 10 조건 (값 동일)")]),
"둘의 관계: SG 가 공격면을 \"인터넷 전체 → CloudFront 대역\" 으로 줄이고, 헤더가 그 안에서 \"우리 배포만\" 골라낸다. 하나만 있으면 구멍이 남는다.",
"# 2. 비밀값은 어디에 있고 어떻게 지키나",
T([("항목", "내용"),
   ("저장", "Terraform 변수 `origin_verify_secret` — `terraform.tfvars`(gitignore) 에만. 노션·저장소·채팅에 적지 않는다"),
   ("두 곳에 같은 값", "① CloudFront 오리진 `alb-public` 의 커스텀 헤더 ② ALB 리스너 규칙 10 의 헤더 조건 — Terraform 이 한 변수에서 둘 다 넣어 불일치가 없다"),
   ("콘솔에서 보면", "CloudFront 오리진 설정엔 값이 보이고, ALB 규칙에도 조건 값이 보인다 — 콘솔 접근 권한 자체가 비밀 접근 권한"),
   ("교체(rotate)", "새 값으로 tfvars 수정 → apply. CloudFront 배포 갱신(수 분) 동안 잠깐 불일치가 생기므로 **규칙에 옛 값·새 값 둘 다 두었다가** 배포 완료 후 옛 값 제거하는 것이 무중단 방법(현재 코드는 단일 값 · 개선 여지)"),
   ("헤더 이름", "`X-Origin-Verify` 는 관례. 이름은 비밀이 아니고 값이 비밀")]),
"# 3. WAF 와의 관계",
"WAF(관리형 규칙 · rate-all 2,000/5분 · rate-booking 100/5분)는 **CloudFront 에 붙어** 있다. 우회 ①②가 성공하면 WAF 를 통째로 건너뛰므로, 오리진 보호는 곧 **WAF 를 의미 있게 만드는 장치**다. 멘토링에서 \"WAF 관리 어려움\" 얘기가 나왔지만 팀은 유지 결정 — 그 결정이 유효하려면 이 4단계가 반드시 있어야 한다.",
"# 4. 눈으로 확인",
code("bash", f"# 1) 우회 ① — 내 PC 에서 ALB 로 직접: SG 에서 버려져 타임아웃(000)\ncurl -sk -m 8 -o /dev/null -w \"%{{http_code}}\\n\" https://{CF_ALB}/\n\n# 2) 우회 ② 흉내 — SG 는 통과했다고 치고 도장 없이 리스너에 닿으면 403 (Bastion 안에서: Bastion 은 VPC 안이라 SG 의 접두사 규칙과 무관하게… 아님! Bastion SG 도 목록에 없어 역시 타임아웃)\n#    → 대신 CloudFront 를 거친 정상 요청과 비교: via 헤더가 있고 200\ncurl -sI https://petclinic.mission-critical.site/ | grep -iE \"^HTTP|^via\"\n\n# 3) 규칙 10 의 헤더 이름만 확인 (값은 콘솔에서만)\nL=$(aws elbv2 describe-listeners --load-balancer-arn $(aws elbv2 describe-load-balancers --names mc-alb-public --profile mc-deploy --query 'LoadBalancers[0].LoadBalancerArn' --output text) --profile mc-deploy --query 'Listeners[0].ListenerArn' --output text)\naws elbv2 describe-rules --listener-arn $L --profile mc-deploy --query 'Rules[?Priority==`10`].Conditions[0].HttpHeaderConfig.HttpHeaderName' --output text\n\n# 4) CloudFront 오리진에 커스텀 헤더가 붙어 있는지 (이름만)\naws cloudfront get-distribution-config --id E2PWXW3LUYTDEE --profile mc-deploy --query 'DistributionConfig.Origins.Items[?Id==`alb-public`].CustomHeaders.Items[].HeaderName' --output text\n\n# 5) SG 인바운드가 접두사 목록 한 줄인지 (0단계와 동일)\naws ec2 describe-security-group-rules --profile mc-deploy --region ap-northeast-2 --filters Name=group-id,Values=$(aws ec2 describe-security-groups --profile mc-deploy --region ap-northeast-2 --filters Name=group-name,Values=mc-sg-alb-public --query 'SecurityGroups[0].GroupId' --output text) --query 'SecurityGroupRules[?IsEgress==`false`].[FromPort,PrefixListId,CidrIpv4]' --output table"),
T([("확인", "기대 결과", "배우는 것"),
   ("1", "`000`(8초 타임아웃)", "SG 1차 — 연결 자체가 안 됨(거부 응답도 없음 = 상태 저장 방화벽이 SYN 을 버림)"),
   ("2", "`HTTP/2 200` + `via: 1.1 ….cloudfront.net`", "정상 경로에만 응답이 있다"),
   ("3", "`X-Origin-Verify`", "규칙이 이 헤더를 본다"),
   ("4", "`X-Origin-Verify`", "CloudFront 가 이 헤더를 붙인다 — 두 곳이 같은 이름"),
   ("5", "`443 pl-22a6434b None`", "CIDR 이 아니라 접두사 목록")]),
"# 5. 다음 단계 진입 기준",
Q("Q1. SG 만으로 충분하지 않은 이유를 한 문장으로.", "CloudFront origin-facing IP 대역은 AWS 의 모든 고객이 공유하므로, 남이 자기 배포의 오리진을 우리 ALB 로 지정하면 SG 는 통과한다."),
Q("Q2. 헤더만으로 충분하지 않은 이유는?", "충분할 수도 있지만, SG 없이는 인터넷 전체가 리스너까지 닿아 TLS 핸드셰이크·규칙 평가를 소모시키고(DDoS 표면), 비밀값 유출 시 즉시 전면 노출. SG 가 표면을 줄여 준다."),
Q("Q3. 비밀값이 유출됐다. 무엇을 하나?", "tfvars 의 `origin_verify_secret` 을 새 값으로 바꿔 apply(CloudFront + ALB 규칙 동시 갱신). 무중단이 필요하면 규칙에 새·옛 값을 잠시 병행."),
"# 6. 읽을 자료", "- AWS 문서 — *Restricting access to Application Load Balancers* (이 설계의 원문)", "- AWS 블로그 — *Limit access to your origins using the AWS-managed prefix list for Amazon CloudFront*", "- 콘솔 구축 가이드 **2-3 오리진 표 · 4-3** 절",
road(4, "")]))

# ---------------- 5 health check ----------------
pages[5] = ("5단계 — 헬스체크 설계: 얕게 볼 것과 깊게 볼 것, 숫자의 뜻", "5️⃣", "\n".join([
goal("🩺", "**이 단계의 목표**: ALB 가 \"이 서버 살아있나\" 를 판단하는 방식과, WEB 은 얕게·WAS 는 깊게 보는 이유, 10s·5s·2/3·30s 가 실제로 몇 초를 뜻하는지. 반나절 분량."),
"# 0. 두 대상 그룹의 헬스체크 비교",
T([("", "mc-tg-web (WEB)", "mc-tg-was (WAS)"),
   ("경로", "`/health.html` — Apache 가 직접 주는 정적 파일 `ok`", "`/petclinic/` — Tomcat 의 앱 홈(Spring 컨텍스트가 떠야 200)"),
   ("무엇을 증명", "**Apache 프로세스가 살아 요청을 받는다** (얕게)", "**Tomcat + 앱 + (초기화 시) DB** 까지 정상 (깊게)"),
   ("간격 · 타임아웃", "10s · 5s", "10s · 5s"),
   ("정상 / 비정상 임계값", "2 / 3", "2 / 3"),
   ("등록 취소 지연", "30s", "30s"),
   ("성공 코드", "200", "200 (슬래시 없으면 301 이라 실패 — 경로에 `/` 필수)")]),
"# 1. 왜 WEB 은 얕게 보나",
"WEB 헬스체크를 `/petclinic/`(프록시 경유) 로 하면 **WAS 가 죽었을 때 WEB 까지 unhealthy** 가 된다. 그러면 ALB 는 보낼 곳이 없어 503 — 사실 Apache 는 멀쩡해서 랜딩 `/` 와 점검 안내는 줄 수 있는데도. 계층마다 **자기 계층만** 검사하고, WAS 장애는 Internal ALB 의 헬스체크 + `mc-was-unhealthy-host` 알람이 잡는다. `SetEnvIf … nolog` 로 헬스체크 요청은 access_log 에서 뺀다(10초마다 두 노드가 찍으면 로그가 헬스체크로 가득 참).",
"# 2. 숫자를 시간으로 번역",
T([("설정", "뜻", "실제 시간"),
   ("간격 10s", "노드마다 10초에 한 번 GET", "ALB 노드가 2개라 서버 입장에선 ~5초에 한 번 요청이 옴"),
   ("타임아웃 5s", "5초 안에 200 이 안 오면 그 회차 실패", "—"),
   ("비정상 임계값 3", "연속 3회 실패해야 unhealthy", "장애 발생 → 제외까지 **최대 약 30초**(10s×3) + 타임아웃"),
   ("정상 임계값 2", "연속 2회 성공해야 다시 healthy", "복구 → 재투입까지 **약 20초**"),
   ("등록 취소 지연 30s", "대상을 뺄 때(교체·축소) 진행 중인 요청을 30초 기다려 줌(draining)", "롤링 교체 때 끊김 없이. 새 요청은 즉시 안 감")]),
"9/16 저녁 롤링 교체 실측: 새 인스턴스가 healthy 되기까지 WEB ≈ 2분(Apache 설치 + index 복사), WAS ≈ 6분(Tomcat 다운로드 + Maven 빌드 + Proxy 로그인 대기). 그래서 ASG 를 켤 때 `health_check_grace_period` 를 WEB 300s · WAS 900s 로 잡아 두었다(10단계).",
"# 3. 헬스체크가 실패하면 실제로 무슨 일이",
"1. 대상 상태 `unhealthy` → 대상 그룹이 그 서버로 **새 요청을 안 보냄**(진행 중인 건 끝까지)\n2. 정상 대상이 하나라도 남으면 사용자는 모름(다른 서버가 받음)\n3. 정상 대상이 **0** 이면 ALB 가 **503** → CloudFront 가 `/maintenance.html` 을 503 으로 보여줌(9단계)\n4. 지표 `UnHealthyHostCount` 가 오르고, WAS 쪽은 알람 `mc-was-unhealthy-host`(≥1, 2분) → SNS",
"# 4. 눈으로 확인",
code("bash", "TG=$(aws elbv2 describe-target-groups --names mc-tg-web --profile mc-deploy --query 'TargetGroups[0].TargetGroupArn' --output text)\n# 1) 헬스체크 설정\naws elbv2 describe-target-groups --target-group-arns $TG --profile mc-deploy --query 'TargetGroups[0].[HealthCheckPath,HealthCheckIntervalSeconds,HealthCheckTimeoutSeconds,HealthyThresholdCount,UnhealthyThresholdCount,Matcher.HttpCode]' --output table\n# 2) 현재 상태 + 이유\naws elbv2 describe-target-health --target-group-arn $TG --profile mc-deploy --query 'TargetHealthDescriptions[].[Target.Id,TargetHealth.State,TargetHealth.Reason]' --output table\n# 3) WEB 의 헬스체크 파일 (Bastion 경유)\nssh -i infra/terraform-kdt5/.keys/mc-ssh.pem -J ec2-user@52.78.145.87 ec2-user@10.0.10.189 'curl -si http://localhost/health.html | head -1; cat /var/www/html/health.html'\n# 4) 실험(선택): web-a 의 httpd 를 40초 멈추고 상태 변화 관찰 → 30초쯤 뒤 unhealthy, 켜면 20초 뒤 healthy\n#   sudo systemctl stop httpd; sleep 40; sudo systemctl start httpd  (다른 터미널에서 2) 를 5초마다 반복)"),
"# 5. 다음 단계 진입 기준",
Q("Q1. WEB 헬스체크를 `/petclinic/` 로 바꾸면 어떤 장애 때 손해인가?", "WAS 만 죽었을 때. Apache 는 살아있는데도 WEB 2대가 전부 unhealthy 로 빠져 503 이 된다. 얕은 체크면 WEB 은 남아 랜딩·점검 안내가 가능."),
Q("Q2. 서버가 죽고 사용자가 영향을 받을 수 있는 최대 시간은?", "약 30초(10s 간격 × 비정상 3회) — 그동안 라운드로빈으로 그 서버에 간 요청은 실패(502/504). 두 대라 절반의 요청."),
Q("Q3. 등록 취소 지연 30초는 언제 쓰이나?", "인스턴스 교체·축소로 대상을 뺄 때. 새 요청은 즉시 안 보내고 진행 중인 요청만 30초까지 마무리시킨다(연결 드레이닝)."),
"# 6. 읽을 자료", "- AWS 문서 — *Health checks for your target groups*", "- AWS 문서 — *Deregistration delay*", "- 콘솔 구축 가이드 **4-2 · ⑥** 절",
road(5, "")]))

# ---------------- 6 Apache ----------------
pages[6] = ("6단계 — Apache 리버스 프록시: petclinic.conf 를 한 줄씩", "6️⃣", "\n".join([
goal("🪶", "**이 단계의 목표**: WEB 서버에서 실제로 돌아가는 `/etc/httpd/conf.d/petclinic.conf` 의 모든 줄을 \"왜 있나\" 로 설명할 수 있게. 이 파일은 `user_data/web.sh` 가 부팅 때 만든다. 하루 분량."),
"# 0. 역할 — Apache 는 두 가지를 한다",
T([("경로", "Apache 가 하는 일", "이유"),
   ("`/` · `/static/*` · `/images/*` · `/health.html`", "**직접 서빙**(파일)", "랜딩 페이지·자산·헬스체크는 WAS 없이도 줘야 한다 (`/static/*` `/images/*` 는 지금 CloudFront → S3 가 먼저 받지만 Apache 에도 사본이 있어 폴백)"),
   ("`/petclinic/*`", "**리버스 프록시** → Internal ALB :8080 → Tomcat", "앱은 WAS 가. WEB 은 WAS 의 IP 를 모르고 Internal ALB 이름만 안다 → WAS 교체·증설 시 WEB 무변경")]),
"# 1. 실제 파일 (web-a, 9/17)",
code("apache", "ProxyPreserveHost On\nRewriteEngine On\nRewriteCond %{HTTP:X-Forwarded-Proto} =https\nRewriteRule ^/petclinic/$ https://%{HTTP_HOST}/ [R=302,L]\nRewriteRule ^/petclinic/$ / [R=302,L]\nRewriteCond %{HTTP:X-Forwarded-Proto} =https\nRewriteRule ^/petclinic$ https://%{HTTP_HOST}/petclinic/ [R=301,L]\nRewriteRule ^/petclinic$ /petclinic/ [R=301,L]\nProxyPass        /health.html !\nProxyPass        /static/ !\nProxyPass        /images/ !\nAlias            /images/ /var/www/html/static/images/\nProxyPass        /petclinic/ http://internal-mc-alb-internal-692352220.ap-northeast-2.elb.amazonaws.com:8080/petclinic/\nProxyPassReverse /petclinic/ http://internal-mc-alb-internal-692352220.ap-northeast-2.elb.amazonaws.com:8080/petclinic/\nSetEnvIf Request_URI \"^/health.html$\" nolog\nCustomLog /var/log/httpd/access_log combined env=!nolog"),
"# 2. 한 줄씩",
T([("줄", "뜻", "없으면"),
   ("`ProxyPreserveHost On`", "프록시할 때 원래 `Host`(petclinic.mission-critical.site)를 그대로 넘김. 기본은 오리진 주소(Internal ALB 이름)로 바꿈", "Tomcat 이 만드는 리다이렉트·절대 링크가 `internal-mc-alb-…:8080` 이 되어 사용자 브라우저가 못 여는 주소를 받음"),
   ("`RewriteEngine On`", "mod_rewrite 켜기", "아래 RewriteRule 전부 무시"),
   ("`RewriteCond … X-Forwarded-Proto =https` + `RewriteRule ^/petclinic/$ https://%{HTTP_HOST}/ [R=302,L]`", "앱 홈 `/petclinic/` 로 오면 랜딩 `/` 로 302 — 단 원래 요청이 https 였으면 Location 도 https 로", "히어로 화면이 두 번(랜딩 + welcome.jsp) 보임 · https 조건 없으면 `Location: http://…` → CloudFront 가 다시 https 로 → **루프**"),
   ("`RewriteRule ^/petclinic/$ / [R=302,L]`", "위 조건이 안 맞을 때(평문 직접 접근)의 폴백", "—"),
   ("`^/petclinic$ → /petclinic/ [R=301]`", "슬래시 없는 `/petclinic` 을 `/petclinic/` 로(Tomcat 컨텍스트 경로 규칙). 마찬가지로 https 조건", "Tomcat 이 자기 주소로 301 을 만들어 위와 같은 문제"),
   ("`ProxyPass /health.html !`", "`!` = **프록시 제외**. 이 경로는 Apache 가 직접", "헬스체크가 WAS 까지 감 → 5단계의 '얕게' 가 깨짐"),
   ("`ProxyPass /static/ !` · `/images/ !`", "정적 자산도 제외 → 파일로 서빙", "정적 요청이 WAS 로 가서 404"),
   ("`Alias /images/ /var/www/html/static/images/`", "URL `/images/…` 를 디스크 `/var/www/html/static/images/…` 에 매핑. WAS 의 welcome.jsp 가 옛 경로 `/images/hero/hero.mp4` 를 쓰기 때문", "hero.mp4 404 (9/16 실제로 겪음)"),
   ("`ProxyPass /petclinic/ http://internal-…:8080/petclinic/`", "핵심. `/petclinic/` 이하를 Internal ALB 로 전달(mod_proxy_http)", "앱 없음"),
   ("`ProxyPassReverse …`", "WAS 응답의 `Location` 헤더 안 주소가 내부 주소면 바깥 주소로 되돌려 씀", "WAS 가 리다이렉트할 때 사용자에게 내부 주소가 노출"),
   ("`SetEnvIf Request_URI \"^/health.html$\" nolog` + `CustomLog … env=!nolog`", "헬스체크 요청은 `nolog` 표시 → 로그에서 제외", "10초마다 ALB 노드 2개가 찍는 줄로 access_log 가 가득 참")]),
"순서가 중요: `ProxyPass … !`(제외)가 `ProxyPass /petclinic/`(전달)보다 **위**에 있어야 한다. mod_proxy 는 위에서부터 첫 매치를 쓴다.",
"# 3. mod_proxy_http 인가 mod_jk 인가",
T([("", "mod_proxy_http (우리)", "mod_jk (AJP)"),
   ("프로토콜", "HTTP — 중간에 **ALB 를 둘 수 있다**", "AJP(바이너리) — ALB 가 못 알아들음 → WEB 이 WAS IP 를 직접 알아야 함"),
   ("WAS 교체·증설", "Internal ALB 가 흡수, WEB 무변경", "workers.properties 수정 + 재시작"),
   ("성능", "요즘 차이 미미(keep-alive 로 연결 재사용)", "약간 유리했던 시절의 선택"),
   ("결론", "3-Tier + ALB 구조면 mod_proxy_http", "ALB 없이 WEB↔WAS 1:1 고정일 때만")]),
"# 4. 눈으로 확인 (Bastion 경유)",
code("bash", "ssh -i infra/terraform-kdt5/.keys/mc-ssh.pem -J ec2-user@52.78.145.87 ec2-user@10.0.10.189\n# 1) 파일 그대로\ncat /etc/httpd/conf.d/petclinic.conf\n# 2) 로드된 모듈 — proxy_http · rewrite · alias 가 있어야\nhttpd -M 2>/dev/null | grep -E \"proxy_http|rewrite|alias|mpm\"\n# 3) 직접 서빙 vs 프록시 vs 리다이렉트\ncurl -si http://localhost/ | head -1                                   # 200 (index.html)\ncurl -si http://localhost/health.html | head -1                        # 200 (ok)\ncurl -si http://localhost/petclinic/ | grep -E \"^HTTP|^Location\"       # 302 Location: /   (평문이라 https 조건 불일치 → 폴백 규칙)\ncurl -si -H \"X-Forwarded-Proto: https\" -H \"Host: petclinic.mission-critical.site\" http://localhost/petclinic/ | grep -E \"^HTTP|^Location\"   # 302 Location: https://petclinic.mission-critical.site/\ncurl -si http://localhost/petclinic | grep -E \"^HTTP|^Location\"        # 301 → /petclinic/\ncurl -si http://localhost/petclinic/vets | head -1                     # 200 — Internal ALB 를 거쳐 Tomcat 이 답한 것\n# 4) 헬스체크가 로그에 없는지\nsudo tail -20 /var/log/httpd/access_log | grep -c health.html           # 0"),
"# 5. 다음 단계 진입 기준",
Q("Q1. `ProxyPreserveHost On` 을 끄면 사용자가 어떤 증상을 보나?", "Tomcat 이 만드는 리다이렉트(예: 폼 제출 후)가 `http://internal-mc-alb-internal-…:8080/…` 로 와서 브라우저가 열지 못한다(내부 이름·사설망)."),
Q("Q2. RewriteRule 앞의 RewriteCond(X-Forwarded-Proto) 를 지우면?", "Apache 는 평문으로 받으니 `Location: http://…/` 를 준다 → CloudFront 가 http→https 리다이렉트 → 다시 Apache → 무한 루프 또는 혼합 콘텐츠."),
Q("Q3. `ProxyPass /health.html !` 을 `ProxyPass /petclinic/` 아래로 옮기면?", "위에서 첫 매치라 `/health.html` 은 `/petclinic/` 과 안 겹쳐 사실 동작은 같다. 하지만 `/static/ !` 처럼 겹칠 수 있는 제외 규칙은 반드시 위에 — 습관적으로 제외를 먼저."),
"# 6. 읽을 자료", "- Apache 문서 — *mod_proxy* (`ProxyPass`, `ProxyPassReverse`, `ProxyPreserveHost`, `!` 제외)", "- Apache 문서 — *mod_rewrite* (`RewriteCond %{HTTP:…}`, 플래그 `R` `L`)", "- 저장소 `infra/terraform-kdt5/modules/base/user_data/web.sh` (이 파일을 만드는 스크립트 · 콘솔 가이드 ⑤ 5-2)",
road(6, "")]))

# ---------------- 7 distribution/timeouts ----------------
pages[7] = ("7단계 — 분산 동작과 타임아웃: 누가 받나, 언제 끊기나", "7️⃣", "\n".join([
goal("⏱️", "**이 단계의 목표**: 요청이 두 WEB 중 어디로 가는지(분산), 연결이 언제 끊기는지(타임아웃)를 ALB·CloudFront·Apache 세 곳의 값으로 맞춰 본다. 값이 어긋나면 나는 502·504 의 원인이 여기. 반나절 분량."),
"# 1. 분산 — 누가 받나",
T([("설정", "우리 값", "뜻"),
   ("알고리즘", "`round_robin`", "정상 대상에 번갈아. 대안 `least_outstanding_requests`(처리 중 요청이 적은 쪽) — 요청 길이가 들쭉날쭉하면 그쪽이 낫다"),
   ("교차 영역(cross-zone)", "**on**", "2a 노드가 받은 요청을 2c 서버로도 보냄 → 서버 대수가 AZ 별로 달라도 균등. ALB 는 기본 on"),
   ("스티키 세션", "**off**", "PetClinic 은 세션에 의존하지 않는 무상태 앱. 켜면 특정 서버로 쏠려 분산이 깨짐"),
   ("slow start", "0", "새 대상에 처음부터 100% 보냄. 워밍업이 필요한 JVM(WAS)엔 30~60s 를 줄 수 있음(로드맵)"),
   ("HTTP/2", "ALB `routing.http2.enabled=true`", "뷰어(CloudFront)와의 얘기. **오리진 쪽은 항상 HTTP/1.1** — CloudFront→ALB 도, ALB→Apache 도")]),
"# 2. 타임아웃 — 세 곳의 값을 한 줄에",
code("text", "CloudFront ──(응답 대기 30s · keep-alive 5s)──▶ ALB ──(유휴 60s)──▶ Apache ──(Timeout 60 · KeepAliveTimeout 5 · MaxKeepAliveRequests 100 = AL2023 기본값)──▶ Internal ALB ──▶ Tomcat"),
T([("지점", "값", "의미", "어긋나면"),
   ("CloudFront 오리진 응답 제한", "**30s**", "ALB 가 30초 안에 첫 바이트를 안 주면 CloudFront 가 **504** 로 사용자에게", "느린 페이지(리포트 등)가 30초 넘으면 사용자는 504 + 점검 페이지 — 실제 서버는 계속 처리 중(낭비)"),
   ("CloudFront 오리진 keep-alive", "5s", "ALB 로의 연결을 5초 유휴까지 재사용", "—"),
   ("ALB 유휴 제한", "**60s**", "클라이언트·대상 양쪽 연결이 60초 동안 데이터가 없으면 ALB 가 끊음", "Apache 의 KeepAliveTimeout 이 이보다 **길어야** 안전: Apache 가 먼저 끊으면 ALB 가 닫힌 연결에 요청을 써서 **502**"),
   ("Apache KeepAliveTimeout", "**5s (기본)**", "Apache 가 유휴 연결을 5초 뒤 닫음", "⚠️ 60s 보다 짧다 — 이론상 502 위험. 다만 ALB 는 대상 연결을 끊기 전에 재시도하고 실측 5XX 0 이라 현재 문제는 없음. 안전하게 하려면 `KeepAliveTimeout 75` (권고: ALB 유휴 + 여유)"),
   ("Apache Timeout", "60s (기본)", "한 요청의 I/O 가 60초 멈추면 끊음", "ALB 60s 와 같음 — 동시에 끊겨 애매. 65~70 으로 두면 ALB 가 먼저 판단")]),
"AWS 권고: **대상(Apache)의 keep-alive 타임아웃 > ALB 유휴 타임아웃**. 우리 web.sh 는 Apache 기본값을 안 건드린다 — 개선 항목(아래 실습 4).",
"# 3. 어디서 몇 초를 세나 — 상태 코드로 역추적",
T([("사용자가 본 것", "누가 냈나", "원인 후보"),
   ("504 + 점검 페이지", "CloudFront (30s) 또는 ALB (60s)", "WAS 가 느림(DB 쿼리 · GC) · Internal ALB 뒤 응답 없음"),
   ("502", "ALB", "Apache 가 연결을 먼저 닫음(keep-alive 불일치) · Apache 응답이 깨짐 · 프로세스 재시작 중"),
   ("503", "ALB", "정상 대상 0 (5단계)")]),
"# 4. 눈으로 확인",
code("bash", "# 1) ALB 속성 — 유휴 60 · 교차 영역 · http2\nALB=$(aws elbv2 describe-load-balancers --names mc-alb-public --profile mc-deploy --query 'LoadBalancers[0].LoadBalancerArn' --output text)\naws elbv2 describe-load-balancer-attributes --load-balancer-arn $ALB --profile mc-deploy --query 'Attributes[?Key==`idle_timeout.timeout_seconds`||Key==`load_balancing.cross_zone.enabled`||Key==`routing.http2.enabled`].[Key,Value]' --output table\n# 2) 대상 그룹 — 알고리즘 · 스티키 · slow start\nTG=$(aws elbv2 describe-target-groups --names mc-tg-web --profile mc-deploy --query 'TargetGroups[0].TargetGroupArn' --output text)\naws elbv2 describe-target-group-attributes --target-group-arn $TG --profile mc-deploy --query 'Attributes[?Key==`load_balancing.algorithm.type`||Key==`stickiness.enabled`||Key==`slow_start.duration_seconds`].[Key,Value]' --output table\n# 3) CloudFront 오리진 — 응답 30 · keep-alive 5\naws cloudfront get-distribution-config --id E2PWXW3LUYTDEE --profile mc-deploy --query 'DistributionConfig.Origins.Items[?Id==`alb-public`].CustomOriginConfig.[OriginReadTimeout,OriginKeepaliveTimeout]' --output table\n# 4) Apache 값 (Bastion 경유) — 아무것도 안 나오면 기본값(KeepAliveTimeout 5 · Timeout 60)\nssh -i infra/terraform-kdt5/.keys/mc-ssh.pem -J ec2-user@52.78.145.87 ec2-user@10.0.10.189 'grep -rhE \"^\\s*(Timeout|KeepAlive|KeepAliveTimeout|MaxKeepAliveRequests)\\b\" /etc/httpd/conf /etc/httpd/conf.d; httpd -M 2>/dev/null | grep mpm'\n# 5) 분산이 실제로 번갈아 가는지 — 서버마다 다른 값이 없어 ALB 로그의 target 필드로 본다 (8단계)\n#    응답 헤더로 보려면 web.sh 에 `Header set X-Served-By \"%{HOSTNAME}e\"` 를 넣는 방법이 있다(로드맵)"),
"# 5. 다음 단계 진입 기준",
Q("Q1. Apache KeepAliveTimeout 5 · ALB 유휴 60 이면 이론상 무엇이 위험한가?", "Apache 가 유휴 연결을 먼저 닫아, ALB 가 그 연결에 다음 요청을 보냈을 때 502. 권고는 대상 > ALB (예: 75s)."),
Q("Q2. 사용자가 504 를 봤다. CloudFront 와 ALB 중 누가 냈는지 어떻게 구분하나?", "ALB 액세스 로그의 `elb_status_code` 가 504 면 ALB(60s), 로그에 요청이 200 인데 사용자는 504 면 CloudFront(30s) 가 먼저 포기한 것. 8단계."),
Q("Q3. 스티키 세션을 켜야 하는 앱은?", "서버 메모리에 세션을 두는 앱(로그인 상태 등). PetClinic 은 세션이 없어 불필요. 필요해지면 ElastiCache(Redis) 로 세션을 밖으로 빼는 게 스티키보다 낫다(멘토링 질문지)."),
"# 6. 읽을 자료", "- AWS 문서 — *Application Load Balancer idle timeout* · *Cross-zone load balancing*", "- Apache 문서 — *KeepAliveTimeout* · *mod_mpm_event*", "- 콘솔 구축 가이드 **4-3 속성 · 2-3 오리진** 절",
road(7, "")]))

# ---------------- 8 observability ----------------
pages[8] = ("8단계 — WEB 관측: 로그 한 줄과 지표 네 개로 무슨 일이 있었는지 알기", "8️⃣", "\n".join([
goal("🔎", "**이 단계의 목표**: ALB 액세스 로그 한 줄을 필드별로 읽고, Apache 로그에서 진짜 클라이언트 IP 를 찾고, CloudWatch 지표 4개로 \"ALB 잘못인지 서버 잘못인지\" 를 가르는 법. 하루 분량."),
"# 1. ALB 액세스 로그 — 실제 한 줄 (9/17 · S3 `mc-logs/alb/public/`)",
code("text", "https 2026-09-17T02:35:37.491476Z app/mc-alb-public/0780e6e7d84abe76 3.172.65.112:63554 10.0.10.189:80 0.001 0.001 0.000 404 404 889 427 \"GET https://petclinic.mission-critical.site:443/favicon.ico HTTP/1.1\" \"Mozilla/5.0 …\" TLS_AES_128_GCM_SHA256 TLSv1.3 arn:…:targetgroup/mc-tg-web/5ae742de9f467369 \"Root=1-6aab51f9-…\" \"petclinic.mission-critical.site\" \"session-reused\" 10 2026-09-17T02:35:37.489000Z \"forward\" \"-\" \"-\" \"10.0.10.189:80\" \"404\" \"-\" \"-\" TID_… \"-\" \"-\" \"-\" 3.34.116.99 \"-\" \"-\""),
T([("필드", "값", "뜻"),
   ("type", "`https`", "리스너 프로토콜"),
   ("client:port", "`3.172.65.112:63554`", "**CloudFront 엣지** IP — 진짜 사용자 IP 는 아님(그건 X-Forwarded-For · Apache 로그)"),
   ("target:port", "`10.0.10.189:80`", "**web-a** 가 받았다 (분산 확인은 이 필드)"),
   ("request_processing / target_processing / response_processing", "`0.001 0.001 0.000`", "ALB 가 대상에 보내기까지 · **대상이 응답하는 데 걸린 시간** · 응답을 돌려주기까지. 느리면 두 번째 값이 큼"),
   ("**elb_status_code** / **target_status_code**", "`404 404`", "ALB 가 사용자에게 준 코드 / 대상이 ALB 에 준 코드. **둘이 다르면 ALB 가 스스로 낸 것**(503 · 504 · 460 · 규칙 403 은 target 이 `-`)"),
   ("request", "`GET https://petclinic.mission-critical.site:443/favicon.ico HTTP/1.1`", "favicon 없음 → 404 (정상적인 브라우저 동작 · 나중에 favicon 추가하면 사라짐)"),
   ("ssl_cipher · ssl_protocol", "`TLS_AES_128_GCM_SHA256 TLSv1.3`", "2단계의 실물"),
   ("trace_id", "`Root=1-6aab51f9-…`", "X-Ray 추적 ID · Apache 로그와 대조 가능"),
   ("domain_name", "`petclinic.mission-critical.site`", "SNI 로 요청된 이름"),
   ("matched_rule_priority", "`10`", "**규칙 10 이 매치** = 도장 검사 통과(4단계). `0` 이면 기본 작업(403)"),
   ("actions_executed", "`forward`", "규칙의 작업"),
   ("target_status_code_list", "`\"404\"`", "재시도 시 여러 개"),
   ("(뒤쪽) `3.34.116.99`", "", "받은 ALB **노드**의 IP(2c 노드). 0단계의 그 IP")]),
"S3 객체는 5분마다 gzip 으로 생긴다(0바이트 테스트 파일 `ELBAccessLogTestFile` 은 무시). 많이 볼 땐 Athena 로 테이블을 만든다(AWS 문서 예제 그대로 쓰면 됨).",
"# 2. Apache access_log — 진짜 IP 는 어디에",
"AL2023 기본 `combined` 형식은 첫 필드가 **연결 상대 IP = ALB 노드 사설 IP**(10.0.0.212 / 10.0.1.212). 사용자 IP 는 `X-Forwarded-For` 헤더 안에 있는데 combined 는 그걸 안 찍는다. 두 가지 방법:",
code("apache", "# 방법 1 — 로그 형식에 XFF 추가 (web.sh 개선 · 로드맵)\nLogFormat \"%{X-Forwarded-For}i %h %l %u %t \\\"%r\\\" %>s %b \\\"%{Referer}i\\\" \\\"%{User-Agent}i\\\"\" combined_xff\nCustomLog /var/log/httpd/access_log combined_xff env=!nolog\n\n# 방법 2 — mod_remoteip 로 %h 자체를 XFF 의 값으로 바꿈 (RemoteIPHeader X-Forwarded-For · RemoteIPInternalProxy 10.0.0.0/16)"),
"XFF 값 예: `183.98.42.129, 3.172.65.112` — **맨 앞이 사용자**, 그다음이 CloudFront. ALB 는 `xff_header_processing.mode=append` 라 뒤에 덧붙이기만 한다.",
"# 3. CloudWatch 지표 4개 — ALB 잘못인가 서버 잘못인가",
T([("지표 (AWS/ApplicationELB)", "뜻", "어떻게 읽나"),
   ("`HTTPCode_ELB_5XX_Count`", "**ALB 가 만든** 5xx (503 정상 대상 없음 · 504 유휴 초과 · 502 대상 연결 실패)", "이게 오르면 대상 그룹·타임아웃·헬스체크를 본다"),
   ("`HTTPCode_Target_5XX_Count`", "**대상이 돌려준** 5xx (Apache/Tomcat 500 · 502)", "이게 오르면 서버 로그(`/mc/web/error` · `/mc/was/catalina`)를 본다"),
   ("`TargetResponseTime` (p95)", "대상이 응답하는 데 걸린 시간 분포", "알람 `mc-alb-p95-latency` › 2s 3분 — 로그의 target_processing_time 과 같은 것"),
   ("`HealthyHostCount` / `UnHealthyHostCount` (대상 그룹 차원)", "정상/비정상 대상 수", "WEB 은 2/0 이어야. WAS 쪽 `mc-was-unhealthy-host` ≥1 2분 알람"),
   ("`RequestCount` · `ActiveConnectionCount`", "부하", "Phase 3 폭주 실험 때 기준선")]),
"실측(9/17 11시, 지난 1시간): `RequestCount 0` · 5XX 없음 → 알람 `mc-alb-p95-latency` 는 데이터가 없어 `INSUFFICIENT_DATA`(정상 · 트래픽이 없는 것뿐).",
"# 4. 눈으로 확인",
code("bash", "# 1) 최신 ALB 로그 객체 한 줄 (헬스체크 제외)\nK=$(aws s3 ls s3://mc-logs-528821350786/alb/public/ --recursive --profile mc-deploy | grep -v TestFile | tail -1 | awk '{print $4}')\naws s3 cp \"s3://mc-logs-528821350786/$K\" - --profile mc-deploy | zcat | grep -v health.html | tail -3\n# 2) elb 코드와 target 코드가 다른 줄만 (ALB 가 스스로 낸 응답)\naws s3 cp \"s3://mc-logs-528821350786/$K\" - --profile mc-deploy | zcat | awk '$9 != $10'\n# 3) 지표 — 지난 1시간 ALB 5XX vs Target 5XX\nfor m in HTTPCode_ELB_5XX_Count HTTPCode_Target_5XX_Count RequestCount; do echo -n \"$m \"; aws cloudwatch get-metric-statistics --namespace AWS/ApplicationELB --metric-name $m --dimensions Name=LoadBalancer,Value=app/mc-alb-public/0780e6e7d84abe76 --start-time $(date -u -d '-1 hour' +%FT%TZ) --end-time $(date -u +%FT%TZ) --period 3600 --statistics Sum --profile mc-deploy --region ap-northeast-2 --query 'Datapoints[0].Sum' --output text; done\n# 4) Apache 로그는 CloudWatch Logs 에서 (서버 접속 없이)\naws logs tail /mc/web/access --since 1h --profile mc-deploy --region ap-northeast-2 | tail -5\n# 5) 알람 상태\naws cloudwatch describe-alarms --alarm-name-prefix mc- --profile mc-deploy --region ap-northeast-2 --query 'MetricAlarms[].[AlarmName,StateValue]' --output table"),
"# 5. 다음 단계 진입 기준",
Q("Q1. 로그 한 줄에서 \"ALB 가 직접 낸 응답\" 을 어떻게 알아보나?", "`elb_status_code` 와 `target_status_code` 가 다르거나 target 이 `-`. 규칙 403 · 503 · 504 가 그렇다. matched_rule_priority 가 0 이면 기본 작업."),
Q("Q2. Apache access_log 첫 IP 가 10.0.0.212 인 이유와 해결은?", "ALB 노드 사설 IP 다(연결 상대). 사용자 IP 는 X-Forwarded-For 에 있으니 LogFormat 에 `%{X-Forwarded-For}i` 를 넣거나 mod_remoteip 를 쓴다."),
Q("Q3. Target_5XX 는 0 인데 ELB_5XX 가 오른다. 어디를 보나?", "서버는 멀쩡히 응답했다는 뜻. 대상 그룹 정상 대상 수(503), 유휴·응답 시간(504), keep-alive 불일치(502) — 5·7단계 항목."),
"# 6. 읽을 자료", "- AWS 문서 — *Access logs for your Application Load Balancer* (필드 표 · Athena 예제)", "- AWS 문서 — *CloudWatch metrics for your Application Load Balancer*", "- Apache 문서 — *mod_log_config* (`%{header}i`) · *mod_remoteip*", "- 🗂️ CloudWatch Logs 총정리 · 로그 흐름 도면(`docs/architecture-log-flow.png`)",
road(8, "")]))

# ---------------- 9 failure modes ----------------
pages[9] = ("9단계 — 장애 모드: 502 · 503 · 504 가 각각 언제 나고, 사용자는 무엇을 보나", "9️⃣", "\n".join([
goal("🚨", "**이 단계의 목표**: WEB 구간에서 날 수 있는 장애를 상태 코드로 분류하고, 각 경우에 사용자 화면·로그·지표가 어떻게 되는지 미리 안다. 그리고 직접 하나 내 본다. 하루 분량."),
"# 1. 장애 6가지",
T([("#", "상황", "누가 어떤 코드를", "사용자 화면", "로그·지표에서 보이는 것", "복구"),
   ("A", "WEB 1대 httpd 죽음", "약 30초간 그 서버로 간 요청 → ALB **502**(연결 거부). 이후 unhealthy 로 제외되면 정상", "잠깐 502 또는 점검 페이지 → 곧 정상(다른 서버)", "`UnHealthyHostCount 1` · ELB_5XX 소량 · ALB 로그 target `-`", "자동(헬스체크). 서버는 `systemctl restart httpd` 또는 교체"),
   ("B", "WEB 2대 모두 죽음", "정상 대상 0 → ALB **503** → CloudFront 가 `/maintenance.html` 을 **503** 으로", "**점검 페이지**", "`HealthyHostCount 0` · ELB_5XX 급증 · WAF·CloudFront 로그는 정상", "교체(Terraform `-replace`) · ASG 였다면 자동"),
   ("C", "WAS 죽음 (WEB 정상)", "Apache 가 Internal ALB 에서 503 을 받아 그대로 → 사용자 **503** → CloudFront 점검 페이지. 단 `/`·`/static` 은 200", "앱 경로만 점검 페이지, 랜딩은 정상", "`mc-was-unhealthy-host` 알람 · Target_5XX(WEB 대상이 503 을 돌려줌)", "WAS 재시작 · Tomcat 404 면 was.sh 의 자동 재시작 3회"),
   ("D", "느린 응답 (DB 잠금 · GC)", "30초 넘으면 CloudFront **504** · 60초 넘으면 ALB **504**", "점검 페이지 (원인은 DB 인데 화면은 WEB 장애처럼 보임)", "`TargetResponseTime p95` 알람 · RDS `slowquery` 로그(9/17 켬)", "쿼리·풀 확인. 7단계 타임아웃 표"),
   ("E", "도장(헤더) 불일치 (배포 교체 중 값 어긋남)", "ALB 규칙 미매치 → **403** 고정 응답", "403 Forbidden 흰 화면 (점검 페이지 아님 — 4xx 는 오류 응답 대상이 아님)", "ALB 로그 `matched_rule_priority 0` · elb 403 · target `-`", "tfvars 값 일치시켜 apply"),
   ("F", "CloudFront 캐시가 옛 css", "장애는 아니지만 \"화면이 깨짐\" 신고", "레이아웃 깨짐", "x-cache: Hit", "무효화 `/static/*` `/images/*` `/petclinic/resources/*`")]),
"# 2. 점검 페이지가 뜨는 조건 (정확히)",
"CloudFront 사용자 지정 오류 응답: 오리진(ALB)이 **502 · 503 · 504** 를 주면 `/maintenance.html` 을 **503** 으로 대체, 10초 캐시. 오리진 그룹 failover 도 500·502·503·504 에서 S3 로 넘어감(GET 만). **403·404·500 은 그대로** 사용자에게 간다 — 그래서 E 는 흰 403.",
"# 3. 직접 내 보기 — 장애 A (안전 · 30초 · 서비스 유지)",
code("bash", "# 터미널 1: 상태 감시 (5초마다)\nTG=$(aws elbv2 describe-target-groups --names mc-tg-web --profile mc-deploy --query 'TargetGroups[0].TargetGroupArn' --output text)\nwhile true; do date +%T; aws elbv2 describe-target-health --target-group-arn $TG --profile mc-deploy --query 'TargetHealthDescriptions[].[Target.Id,TargetHealth.State]' --output text; sleep 5; done\n\n# 터미널 2: web-a 의 Apache 를 60초 멈춤 (Bastion 경유)\nssh -i infra/terraform-kdt5/.keys/mc-ssh.pem -J ec2-user@52.78.145.87 ec2-user@10.0.10.189 'sudo systemctl stop httpd; sleep 60; sudo systemctl start httpd'\n\n# 터미널 3: 사용자 입장 — 1초마다 상태 코드 (약 30초 동안 절반쯤 502/503 섞이다가 정상)\nfor i in $(seq 1 90); do curl -s -o /dev/null -w \"%{http_code} \" -m 5 https://petclinic.mission-critical.site/; sleep 1; done; echo\n\n# 뒤처리: 5분 뒤 ALB 로그에서 elb 코드 != target 코드 줄 확인 (8단계 2번)"),
"관찰 포인트: (1) 정지 후 몇 초 만에 unhealthy 로 바뀌나(기대 ≈ 30s) (2) 그 사이 사용자 코드에 502 가 몇 개 섞이나 (3) 시작 후 healthy 복귀까지(기대 ≈ 20s) (4) 알람은 WEB 엔 없다 — WAS 만 있음 → WEB 용 `HealthyHostCount < 2` 알람 추가가 로드맵.",
"# 4. 눈으로 확인 (실험 없이)",
code("bash", "# 1) CloudFront 오류 응답 설정 — 502/503/504 → /maintenance.html 503\naws cloudfront get-distribution-config --id E2PWXW3LUYTDEE --profile mc-deploy --query 'DistributionConfig.CustomErrorResponses.Items[].[ErrorCode,ResponseCode,ResponsePagePath,ErrorCachingMinTTL]' --output table\n# 2) 점검 페이지 자체는 지금도 열린다\ncurl -sI https://petclinic.mission-critical.site/maintenance.html | head -1\n# 3) 지난 24시간 ALB 5XX (0 이어야)\naws cloudwatch get-metric-statistics --namespace AWS/ApplicationELB --metric-name HTTPCode_ELB_5XX_Count --dimensions Name=LoadBalancer,Value=app/mc-alb-public/0780e6e7d84abe76 --start-time $(date -u -d '-24 hour' +%FT%TZ) --end-time $(date -u +%FT%TZ) --period 86400 --statistics Sum --profile mc-deploy --region ap-northeast-2 --query 'Datapoints[0].Sum'"),
"# 5. 다음 단계 진입 기준",
Q("Q1. 사용자가 점검 페이지를 본다. WEB 장애인지 WAS 장애인지 1초 안에 가르는 법은?", "랜딩 `/` 를 열어 본다. 200 이면 WEB 은 살아있고 WAS(C) 문제, 점검 페이지면 WEB(B) 또는 ALB. 그다음 대상 그룹 상태."),
Q("Q2. 403 흰 화면은 왜 점검 페이지로 안 바뀌나?", "CloudFront 오류 응답이 502·503·504 만 대체하도록 설정돼 있고, 403 은 '요청 거부' 라 점검 안내가 맞지 않는다. 헤더 불일치(E) 나 WAF 차단이면 403."),
Q("Q3. 한 대 장애 때 사용자가 502 를 잠깐이라도 보는 걸 없애려면?", "헬스체크 간격·임계값을 줄이면(5s · 2회) 제외가 빨라지지만 오탐도 늘어난다. 근본적으로는 대수를 늘리거나(3대면 영향 1/3) ASG 로 자동 교체 + Apache 를 systemd `Restart=always` 로."),
"# 6. 읽을 자료", "- AWS 문서 — *Troubleshoot your Application Load Balancers* (HTTP 502/503/504 원인 표)", "- AWS 문서 — *Generating custom error responses* (CloudFront)", "- 콘솔 구축 가이드 **2-3 오류 응답 · 3-3 점검 페이지**",
road(9, "")]))

# ---------------- 10 ASG/AMI ----------------
pages[10] = ("10단계 — ASG · AMI: 고정 2대에서 자동 교체·증설로", "🔟", "\n".join([
goal("📈", "**이 단계의 목표**: 지금의 고정 EC2 2대가 ASG 로 바뀌면 무엇이 달라지는지, 그때 필요한 부품(시작 템플릿 · 골든 AMI · 종료 훅 · 로그)을 우리 코드(`base.enable_asg`)와 연결한다. 0~9 단계가 전부 이 위에 그대로 올라간다. 하루 분량."),
"# 0. 지금 vs ASG",
T([("", "지금 (enable_asg=false)", "ASG (enable_asg=true)"),
   ("서버", "`aws_instance` 2대 · 이름 mc-web-a/c", "시작 템플릿 `mc-lt-web` + ASG `mc-asg-web` (min 2 · max 4 · desired 2)"),
   ("대상 그룹 등록", "Terraform 이 직접 attach", "ASG 가 `target_group_arns` 로 스스로 등록·해제"),
   ("서버가 죽으면", "unhealthy 로 빠지고 **사람이** 교체", "ELB 헬스체크 실패 → ASG 가 종료 후 **자동으로 새 인스턴스**"),
   ("트래픽 증가", "그대로", "대상 추적: 평균 CPU 60% 유지하도록 증설(WAS 는 대상당 요청 300 도)"),
   ("설정 변경(web.sh)", "인스턴스 교체(`-replace`)", "템플릿 새 버전 → **인스턴스 새로 고침**(Rolling · 50% 유지) — Notion 'AMI & Auto Scaling' 의 v1→v2 절차"),
   ("종료 시 로그", "서버에 없음(Agent 실시간)", "WAS 종료 훅 300s: `mc-lifecycle-watch` 가 마지막 로그 S3 sync 후 CONTINUE")]),
"# 1. 부품",
T([("부품", "뜻", "우리 코드 (`modules/base/compute.tf`)"),
   ("**시작 템플릿**", "\"이런 서버를 만들어라\" 명세: AMI · 유형 · SG · 키 · 프로파일 · **user_data**", "`aws_launch_template.web/was` · `$Latest` 참조 · IMDSv2 · gp3 20G"),
   ("**ASG**", "템플릿으로 서버를 몇 대 유지할지 + 어느 서브넷·대상 그룹", "`aws_autoscaling_group.web/was` · 서브넷 web-a/c · `health_check_type = ELB` · grace WEB 300s / WAS 900s(스톡 AMI 빌드 시간)"),
   ("**스케일링 정책**", "언제 늘리고 줄일지", "대상 추적 `ASGAverageCPUUtilization 60` · WAS 는 `ALBRequestCountPerTarget 300` 추가"),
   ("**인스턴스 새로 고침**", "템플릿이 바뀌면 순차 교체", "`instance_refresh` Rolling · `min_healthy_percentage 50`"),
   ("**종료 수명 주기 훅**", "종료 직전에 시간을 벌어 뒷정리", "`initial_lifecycle_hook` TERMINATING 300s + was.sh 의 `mc-lifecycle-watch.service`"),
   ("**골든 AMI**", "설치가 끝난 이미지. 부팅이 5~8분 → 1~2분", "`base.web_ami_id` / `was_ami_id` — 있으면 was.sh 가 Tomcat 다운로드·clone 을 건너뛰고 WAR 만 재빌드")]),
"# 2. 골든 AMI 를 구울 때 주의 (Notion 'AMI & Auto Scaling' 반영)",
"- **user_data 는 매 부팅 실행되지 않는다** — AMI 로 만든 인스턴스는 cloud-init 이 '첫 부팅' 으로 인식해 실행되지만, 이미 설치된 것을 다시 설치하려 하므로 스크립트가 **멱등**해야 한다. 우리 web.sh 는 `dnf install`(이미 있으면 통과) · 파일 덮어쓰기라 안전. was.sh 는 `baked` 플래그로 분기.\n- **WAR 안에 Proxy 주소·앱 비밀이 박힌다** → 계정·비밀이 바뀌면 AMI 를 다시 굽거나(권장) 부팅 때 재빌드(현재 방식).\n- Notion 페이지의 옛 스크립트(`INTERNAL_ALB=… internal-alb-internal-test-…`)는 kdt5 콘솔 구축본 값 — mc-deploy 에선 `internal-mc-alb-internal-692352220…`. 값을 코드 한 곳(Terraform 변수)에서만 넣는 이유.",
"# 3. DB 초기화 경합 (Notion 'was' 페이지의 우려)",
"ASG 로 WAS 2대가 **동시에** 뜨면 둘 다 `schema.sql` 을 실행한다. 우리 앱은 Spring Boot 가 아니라 XML `jdbc:initialize-database` 이고 MySQL 스크립트가 `CREATE TABLE IF NOT EXISTS` · `INSERT IGNORE` 라 **현재도 멱등** — 9/16 롤링 교체·동시 부팅에서 실측 문제 없음. 더 엄격히 하려면 `base.db_init_mode = \"userdata\"`: was.sh 가 `GET_LOCK` 으로 직렬화해 1회만 실행하고 Spring 초기화는 `-Djdbc.initLocation` 으로 끈다(Java 0줄).",
"# 4. 켜는 순서 (실제 할 때)",
"1. (선택) 콘솔에서 mc-web-a · mc-was-a 로 이미지 생성 → `base.web_ami_id` · `was_ami_id`\n2. `base.enable_asg = true` → plan 에서 **고정 EC2 4대 destroy + LT·ASG create** 확인 → apply. 이 전환은 **다운타임**이 생기므로(고정 EC2 가 먼저 사라짐) 점검 시간에. 무중단이 필요하면 ASG 를 먼저 만들고 대상 그룹에 둘 다 붙인 뒤 고정 EC2 를 빼는 2단계 apply(코드 개선 여지)\n3. 확인: 대상 그룹에 ASG 인스턴스가 healthy · `aws autoscaling describe-auto-scaling-groups`\n4. 템플릿을 고칠 땐 apply → 새 버전 → `start-instance-refresh` 또는 콘솔 \"인스턴스 새로 고침 시작\"",
"# 5. 눈으로 확인 (지금 · 코드만)",
code("bash", "# 1) 지금은 ASG 가 없다\naws autoscaling describe-auto-scaling-groups --profile mc-deploy --region ap-northeast-2 --query 'AutoScalingGroups[].AutoScalingGroupName' --output text   # (mc- 없음)\n# 2) 켰을 때 무엇이 생기는지 코드로 읽기\nsed -n '/# ---------- ASG (enable_asg=true)/,$p' infra/terraform-kdt5/modules/base/compute.tf | grep -E 'resource |name |min_size|max_size|health_check_grace|target_value|heartbeat_timeout'\n# 3) 켜면 plan 이 어떻게 되는지 (apply 안 함)\ncd infra/terraform-kdt5 && terraform plan -no-color -var='base={app_repo_branch=\"test\",tomcat_version=\"9.0.121\",web_index_branch=\"test\",enable_asg=true}' 2>/dev/null | grep -E '^  # |^Plan:'"),
"# 6. 진입 기준 — 여기까지 오면 WEB 계층 한 바퀴",
Q("Q1. ASG 의 헬스체크 유형을 EC2 가 아니라 ELB 로 두는 이유는?", "EC2 상태 검사는 '인스턴스가 켜져 있나' 만 본다. Apache 가 죽어도 EC2 는 정상. ELB 유형이면 대상 그룹 헬스체크(5단계) 실패를 곧 교체 신호로 쓴다."),
Q("Q2. grace period 를 WAS 900s 로 둔 이유는?", "스톡 AMI 에서 Tomcat 다운로드 + Maven 빌드 + Proxy 로그인 대기가 5~8분. 그 전에 ELB 체크가 실패하면 ASG 가 '고장' 으로 보고 끝없이 교체한다. 골든 AMI 면 300s 로 줄일 수 있다."),
Q("Q3. 로그는 ASG 에서 어떻게 지키나?", "서버에 두지 않는다: Agent 가 실시간으로 CloudWatch Logs 로, 스트림 = 인스턴스 ID, 종료 훅 300s 동안 마지막 줄을 S3 로 sync. 인스턴스가 사라져도 로그는 남는다(🗂️ 총정리)."),
"# 7. 읽을 자료", "- Notion — 🤓 AMI & Auto Scaling (팀 콘솔 절차 · v1→v2 교체)", "- AWS 문서 — *Auto Scaling instance refresh* · *Lifecycle hooks* · *Target tracking scaling policies*", "- 저장소 `infra/terraform-kdt5/README.md` 'ASG · AMI' 절 · `modules/base/compute.tf`",
road(10, "")]))

# ---------- write + scan ----------
for n, (title, icon, body) in pages.items():
    p = os.path.join(OUT, f"step{n:02d}.md"); open(p, "w", encoding="utf-8").write(body)
    infence = False; issues = []; fences = 0
    for i, line in enumerate(body.split("\n"), 1):
        if line.strip().startswith("```"): infence = not infence; fences += 1; continue
        if infence or line.startswith(">"): continue
        t = re.sub(r"<td>|</td>|<tr>|</tr>|<table[^>]*>|</table>|<callout[^>]*>|</callout>|<details>|</details>|<summary>|</summary>|<br>", "", line)
        for ch in "<>|{}\\":
            if ch in t: issues.append((i, ch, line.strip()[:70]))
    print(n, title[:30], "fences", fences, "issues", issues[:3])
import json; json.dump({n: {"title": t, "icon": i} for n, (t, i, _) in pages.items()}, open(os.path.join(OUT, "meta.json"), "w"), ensure_ascii=False, indent=1)
